FROM node:18-alpine AS build

WORKDIR /app

# Copy shared first
COPY shared ./shared
WORKDIR /app/shared
RUN npm install && npm run build

# Back to service
WORKDIR /app
COPY renewal-service/package*.json ./
RUN npm install
COPY renewal-service/tsconfig.json ./
COPY renewal-service/src ./src
RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY renewal-service/package*.json ./
RUN npm install --only=production
COPY --from=build /app/dist ./dist

CMD ["npm", "run", "start"]

